"""create_initial_netra_tables

Revision ID: 1c0e9fb651b7
Revises: 
Create Date: 2026-09-21 09:54:42.452446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1c0e9fb651b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('location_name', sa.String(length=256), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('vehicle_count', sa.Integer(), nullable=False),
    sa.Column('speed_avg', sa.String(length=32), nullable=True),
    sa.Column('last_detection', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_vehicles',
    sa.Column('global_vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_class', sa.String(length=64), nullable=False),
    sa.Column('plate_text', sa.String(length=32), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('global_vehicle_id')
    )
    op.create_index(op.f('ix_global_vehicles_plate_text'), 'global_vehicles', ['plate_text'], unique=False)
    op.create_table('camera_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_camera', sa.String(length=64), nullable=False),
    sa.Column('to_camera', sa.String(length=64), nullable=False),
    sa.Column('transition_count', sa.Integer(), nullable=False),
    sa.Column('avg_duration_seconds', sa.Float(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_camera'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_camera'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_camera', 'to_camera', name='uq_from_to_camera')
    )
    op.create_table('cross_camera_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_a', sa.String(length=64), nullable=False),
    sa.Column('track_a', sa.Integer(), nullable=False),
    sa.Column('camera_b', sa.String(length=64), nullable=False),
    sa.Column('track_b', sa.Integer(), nullable=False),
    sa.Column('global_vehicle_id', sa.String(length=64), nullable=True),
    sa.Column('reid_similarity', sa.Float(), nullable=False),
    sa.Column('plate_match', sa.Boolean(), nullable=False),
    sa.Column('class_match', sa.Boolean(), nullable=False),
    sa.Column('available_evidence', sa.JSON(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_a'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['camera_b'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['global_vehicle_id'], ['global_vehicles.global_vehicle_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cross_camera_matches_global_vehicle_id'), 'cross_camera_matches', ['global_vehicle_id'], unique=False)
    op.create_index('ix_match_cameras', 'cross_camera_matches', ['camera_a', 'camera_b'], unique=False)
    op.create_table('license_plates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_text', sa.String(length=32), nullable=False),
    sa.Column('plate_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('vehicle_class', sa.String(length=64), nullable=True),
    sa.Column('last_camera_id', sa.String(length=64), nullable=True),
    sa.Column('last_seen_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_plates_plate_text'), 'license_plates', ['plate_text'], unique=True)
    op.create_table('route_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('global_vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('current_camera', sa.String(length=64), nullable=False),
    sa.Column('vehicle_class', sa.String(length=64), nullable=False),
    sa.Column('prediction_available', sa.Boolean(), nullable=False),
    sa.Column('predictions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_camera'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['global_vehicle_id'], ['global_vehicles.global_vehicle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_predictions_global_vehicle_id'), 'route_predictions', ['global_vehicle_id'], unique=False)
    op.create_table('vehicle_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('global_vehicle_id', sa.String(length=64), nullable=True),
    sa.Column('vehicle_class', sa.String(length=64), nullable=False),
    sa.Column('plate_text', sa.String(length=32), nullable=True),
    sa.Column('plate_status', sa.String(length=32), nullable=False),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('valid_observation_count', sa.Integer(), nullable=False),
    sa.Column('best_ocr_confidence', sa.Float(), nullable=True),
    sa.Column('first_seen_frame', sa.Integer(), nullable=True),
    sa.Column('last_seen_frame', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['global_vehicle_id'], ['global_vehicles.global_vehicle_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_obs_camera_track', 'vehicle_observations', ['camera_id', 'track_id'], unique=False)
    op.create_index(op.f('ix_vehicle_observations_camera_id'), 'vehicle_observations', ['camera_id'], unique=False)
    op.create_index(op.f('ix_vehicle_observations_global_vehicle_id'), 'vehicle_observations', ['global_vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_observations_plate_text'), 'vehicle_observations', ['plate_text'], unique=False)
    op.create_index(op.f('ix_vehicle_observations_track_id'), 'vehicle_observations', ['track_id'], unique=False)
    op.create_table('vehicle_trajectories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('global_vehicle_id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_class', sa.String(length=64), nullable=False),
    sa.Column('plate_text', sa.String(length=32), nullable=True),
    sa.Column('camera_sequence', sa.JSON(), nullable=False),
    sa.Column('total_distance_meters', sa.Float(), nullable=False),
    sa.Column('total_travel_time_seconds', sa.Float(), nullable=False),
    sa.Column('average_speed_kmh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['global_vehicle_id'], ['global_vehicles.global_vehicle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_trajectories_global_vehicle_id'), 'vehicle_trajectories', ['global_vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_trajectories_plate_text'), 'vehicle_trajectories', ['plate_text'], unique=False)
    op.create_table('trajectory_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trajectory_id', sa.Integer(), nullable=False),
    sa.Column('from_camera', sa.String(length=64), nullable=False),
    sa.Column('to_camera', sa.String(length=64), nullable=False),
    sa.Column('from_timestamp', sa.String(length=64), nullable=True),
    sa.Column('to_timestamp', sa.String(length=64), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('cumulative_distance_meters', sa.Float(), nullable=False),
    sa.Column('travel_time_seconds', sa.Float(), nullable=False),
    sa.Column('average_speed_kmh', sa.Float(), nullable=False),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=False),
    sa.Column('minimum_feasible_time_seconds', sa.Float(), nullable=False),
    sa.Column('travel_time_feasible', sa.Boolean(), nullable=False),
    sa.Column('bearing_degrees', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_camera'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_camera'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trajectory_id'], ['vehicle_trajectories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trajectory_segments_trajectory_id'), 'trajectory_segments', ['trajectory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trajectory_segments_trajectory_id'), table_name='trajectory_segments')
    op.drop_table('trajectory_segments')
    op.drop_index(op.f('ix_vehicle_trajectories_plate_text'), table_name='vehicle_trajectories')
    op.drop_index(op.f('ix_vehicle_trajectories_global_vehicle_id'), table_name='vehicle_trajectories')
    op.drop_table('vehicle_trajectories')
    op.drop_index(op.f('ix_vehicle_observations_track_id'), table_name='vehicle_observations')
    op.drop_index(op.f('ix_vehicle_observations_plate_text'), table_name='vehicle_observations')
    op.drop_index(op.f('ix_vehicle_observations_global_vehicle_id'), table_name='vehicle_observations')
    op.drop_index(op.f('ix_vehicle_observations_camera_id'), table_name='vehicle_observations')
    op.drop_index('ix_obs_camera_track', table_name='vehicle_observations')
    op.drop_table('vehicle_observations')
    op.drop_index(op.f('ix_route_predictions_global_vehicle_id'), table_name='route_predictions')
    op.drop_table('route_predictions')
    op.drop_index(op.f('ix_license_plates_plate_text'), table_name='license_plates')
    op.drop_table('license_plates')
    op.drop_index('ix_match_cameras', table_name='cross_camera_matches')
    op.drop_index(op.f('ix_cross_camera_matches_global_vehicle_id'), table_name='cross_camera_matches')
    op.drop_table('cross_camera_matches')
    op.drop_table('camera_transitions')
    op.drop_index(op.f('ix_global_vehicles_plate_text'), table_name='global_vehicles')
    op.drop_table('global_vehicles')
    op.drop_table('cameras')
    # ### end Alembic commands ###
