"""Pydantic Schemas strictly adhering to confirmed AI Engine output JSON contracts.

Confirmed AI Structures:
A. Vehicle Track JSON
B. Cross-Camera Match JSON
C. Global Vehicle JSON
D. Trajectory JSON
E. Route Prediction JSON

Note: No unsupported or fabricated fields are included.
"""
from typing import List, Optional, Any, Union
from pydantic import BaseModel, Field, ConfigDict, model_validator


class VehicleTrackInput(BaseModel):
    """Confirmed AI Vehicle Track item."""
    track_id: int = Field(..., description="Unique track ID generated by camera tracker")
    vehicle_class: str = Field(..., description="Classification e.g. Car, Sedan, Commercial SUV, etc.")
    plate_text: Optional[str] = Field(None, description="Extracted license plate text if OCR succeeded")
    plate_status: Optional[str] = Field("unknown", description="Plate status: stable, tentative, or unknown")
    plate_confidence: Optional[float] = Field(None, ge=0.0, le=100.0, description="Plate detection confidence score")
    observation_count: Optional[int] = Field(0, ge=0, description="Total frames track was observed")
    valid_observation_count: Optional[int] = Field(0, ge=0, description="Frames with valid vehicle features")
    best_ocr_confidence: Optional[float] = Field(None, ge=0.0, le=100.0, description="Highest OCR confidence attained")
    first_seen_frame: Optional[int] = Field(None, ge=0, description="Frame index of initial sighting")
    last_seen_frame: Optional[int] = Field(None, ge=0, description="Frame index of final sighting")
    last_bbox: Optional[List[int]] = Field(None, description="Bounding box coordinates [x1, y1, x2, y2]")
    detector_confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Vehicle detector confidence score")

    @model_validator(mode="before")
    @classmethod
    def _normalize_track_input(cls, data: Any) -> Any:
        if isinstance(data, dict):
            d = dict(data)
            # Map frame_start / frame_end if first_seen_frame / last_seen_frame not present
            if "frame_start" in d and "first_seen_frame" not in d:
                d["first_seen_frame"] = d.pop("frame_start")
            if "frame_end" in d and "last_seen_frame" not in d:
                d["last_seen_frame"] = d.pop("frame_end")
            # Unpack nested plate dict if present
            if "plate" in d and isinstance(d["plate"], dict):
                p = d.pop("plate")
                if "plate_text" not in d:
                    d["plate_text"] = p.get("text")
                if "plate_status" not in d:
                    d["plate_status"] = p.get("status")
                if "plate_confidence" not in d:
                    d["plate_confidence"] = p.get("confidence")
                if "observation_count" not in d:
                    d["observation_count"] = p.get("observation_count")
                if "valid_observation_count" not in d:
                    d["valid_observation_count"] = p.get("valid_observation_count")
                if "best_ocr_confidence" not in d:
                    d["best_ocr_confidence"] = p.get("best_ocr_confidence")
            # Map observation_id -> track_id if track_id not present
            if "observation_id" in d and "track_id" not in d:
                parts = str(d["observation_id"]).split("_")
                try:
                    d["track_id"] = int(parts[-1])
                except (ValueError, IndexError):
                    d["track_id"] = 1
            # Map bbox -> last_bbox if last_bbox not present
            if "bbox" in d and "last_bbox" not in d:
                d["last_bbox"] = d.pop("bbox")
            # Pop extraneous fields from camera observation / reid dumps so extra="forbid" doesn't reject real AI outputs
            d.pop("observation_id", None)
            d.pop("image_name", None)
            d.pop("frame_index", None)
            d.pop("camera_metadata", None)
            d.pop("plate_bbox", None)
            d.pop("camera_id", None)
            d.pop("reid", None)
            d.pop("reid_embedding", None)
            d.pop("representative_embedding", None)
            d.pop("frame_count", None)
            return d
        return data

    model_config = ConfigDict(extra="forbid")


class CameraTracksIngest(BaseModel):
    """Payload for camera track batch ingestion."""
    camera_id: str = Field(..., description="Camera identifier where tracks were captured")
    tracks: List[VehicleTrackInput] = Field(..., min_length=1, description="List of detected vehicle tracks")

    model_config = ConfigDict(extra="forbid")


class CrossCameraMatchInput(BaseModel):
    """Confirmed AI Cross-Camera Match item."""
    camera_a: str = Field(..., description="First camera identifier")
    track_a: int = Field(..., description="Track ID in camera A")
    camera_b: str = Field(..., description="Second camera identifier")
    track_b: int = Field(..., description="Track ID in camera B")
    reid_similarity: Optional[float] = Field(None, ge=-1.0, le=1.0, description="Visual Re-ID embedding cosine similarity")
    plate_match: Optional[bool] = Field(None, description="Whether plate OCR texts match")
    class_match: Optional[Union[float, bool]] = Field(None, description="Whether vehicle classifications match")
    available_evidence: Optional[List[str]] = Field(default_factory=list, description="List of evidence types e.g. ['reid', 'class']")
    match_score: float = Field(..., ge=0.0, le=1.0, description="Combined fusion match score")
    threshold: float = Field(..., ge=0.0, le=1.0, description="Operational decision threshold")
    matched: bool = Field(..., description="Whether match was accepted above threshold")

    @model_validator(mode="before")
    @classmethod
    def _normalize_match_input(cls, data: Any) -> Any:
        if isinstance(data, dict):
            d = dict(data)
            if "observation_a" in d and "track_a" not in d:
                parts = str(d["observation_a"]).split("_")
                try:
                    d["track_a"] = int(parts[-1])
                except (ValueError, IndexError):
                    d["track_a"] = 1
            if "observation_b" in d and "track_b" not in d:
                parts = str(d["observation_b"]).split("_")
                try:
                    d["track_b"] = int(parts[-1])
                except (ValueError, IndexError):
                    d["track_b"] = 1
            if "threshold" not in d:
                d["threshold"] = 0.75
            d.pop("observation_a", None)
            d.pop("observation_b", None)
            d.pop("image_a", None)
            d.pop("image_b", None)
            d.pop("class_a", None)
            d.pop("class_b", None)
            d.pop("plate_a", None)
            d.pop("plate_b", None)
            d.pop("match_status", None)
            d.pop("reason", None)
            return d
        return data

    model_config = ConfigDict(extra="forbid")


class GlobalVehicleObservationRef(BaseModel):
    """Confirmed AI reference inside Global Vehicle observations."""
    camera_id: str = Field(..., description="Camera identifier")
    track_id: int = Field(..., description="Track ID at specified camera")

    @model_validator(mode="before")
    @classmethod
    def _normalize_ref(cls, data: Any) -> Any:
        if isinstance(data, dict):
            d = dict(data)
            if "track_id" not in d and "observation_id" in d:
                parts = str(d["observation_id"]).split("_")
                try:
                    d["track_id"] = int(parts[-1])
                except (ValueError, IndexError):
                    d["track_id"] = 1
            d.pop("observation_id", None)
            d.pop("image_name", None)
            d.pop("vehicle_class", None)
            d.pop("plate_text", None)
            d.pop("plate_status", None)
            d.pop("bbox", None)
            d.pop("detector_confidence", None)
            return d
        return data

    model_config = ConfigDict(extra="forbid")


class GlobalVehicleInput(BaseModel):
    """Confirmed AI Global Vehicle item."""
    global_vehicle_id: str = Field(..., description="Canonical global vehicle UUID or identifier")
    vehicle_class: str = Field(..., description="Vehicle class category")
    observations: Optional[List[GlobalVehicleObservationRef]] = Field(default_factory=list, description="Camera track sightings")
    plate_text: Optional[str] = Field(None, description="Consolidated license plate text")
    match_confidence: Optional[float] = Field(None, ge=0.0, le=100.0, description="Global match confidence")

    @model_validator(mode="before")
    @classmethod
    def _normalize_gv_input(cls, data: Any) -> Any:
        if isinstance(data, dict):
            d = dict(data)
            d.pop("camera_count", None)
            d.pop("observation_count", None)
            d.pop("camera_sequence", None)
            d.pop("representative_embedding", None)
            return d
        return data

    model_config = ConfigDict(extra="forbid")


class TrajectorySegmentInput(BaseModel):
    """Confirmed AI Trajectory Segment item."""
    global_vehicle_id: Optional[str] = Field(None, description="Associated global vehicle identifier")
    from_camera: str = Field(..., description="Origin camera ID")
    to_camera: str = Field(..., description="Destination camera ID")
    from_timestamp: Optional[str] = Field(None, description="Timestamp at origin camera")
    to_timestamp: Optional[str] = Field(None, description="Timestamp at destination camera")
    distance_meters: float = Field(0.0, ge=0.0, description="Segment distance in meters")
    cumulative_distance_meters: float = Field(0.0, ge=0.0, description="Cumulative distance in meters")
    travel_time_seconds: float = Field(0.0, ge=0.0, description="Travel time in seconds")
    average_speed_kmh: float = Field(0.0, ge=0.0, description="Simulation artifact speed (not verified real-world speed)")
    speed_limit_kmh: float = Field(0.0, ge=0.0, description="Corridor speed limit")
    minimum_feasible_time_seconds: float = Field(0.0, ge=0.0, description="Minimum kinematically feasible duration")
    travel_time_feasible: bool = Field(True, description="Whether transit time is physically feasible")
    bearing_degrees: float = Field(0.0, ge=0.0, le=360.0, description="Compass bearing degrees")
    direction: Optional[str] = Field(None, description="Cardinal direction e.g. South-East")
    match_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Cross-camera association fusion score")
    reid_similarity: Optional[float] = Field(None, ge=-1.0, le=1.0, description="Visual Re-ID embedding similarity")
    available_evidence: Optional[List[str]] = Field(default_factory=list, description="List of evidence types e.g. ['reid', 'class']")

    model_config = ConfigDict(extra="forbid")


class TrajectoryInput(BaseModel):
    """Confirmed AI Trajectory item."""
    global_vehicle_id: str = Field(..., description="Associated global vehicle identifier")
    vehicle_class: str = Field(..., description="Vehicle classification")
    plate_text: Optional[str] = Field(None, description="Vehicle plate text")
    camera_sequence: List[str] = Field(..., min_length=1, description="Sequence of camera IDs traversed")
    total_distance_meters: float = Field(0.0, ge=0.0, description="Total trajectory distance in meters")
    total_travel_time_seconds: float = Field(0.0, ge=0.0, description="Total trajectory transit time in seconds")
    average_speed_kmh: float = Field(0.0, ge=0.0, description="Simulation artifact average speed")
    segments: Optional[List[TrajectorySegmentInput]] = Field(default_factory=list, description="Constituent segments")
    observations: Optional[List[dict]] = Field(default_factory=list, description="Constituent camera track observations")

    model_config = ConfigDict(extra="forbid")


class RoutePredictionItemInput(BaseModel):
    """Individual next-camera prediction entry."""
    next_camera: str = Field(..., description="Candidate next camera node")
    probability: float = Field(..., ge=0.0, le=1.0, description="Transition probability score")
    observed_historical_transitions: int = Field(..., ge=0, description="Historical transition count observed")

    model_config = ConfigDict(extra="forbid")


class RoutePredictionInput(BaseModel):
    """Confirmed AI Route Prediction item."""
    global_vehicle_id: str = Field(..., description="Target global vehicle ID")
    current_camera: str = Field(..., description="Current observed camera node")
    vehicle_class: str = Field(..., description="Vehicle classification")
    prediction_available: bool = Field(..., description="Flag indicating if prediction model produced results")
    predictions: List[RoutePredictionItemInput] = Field(default_factory=list, description="Ranked next-camera predictions")

    model_config = ConfigDict(extra="forbid")


class UnifiedAIIngestPayload(BaseModel):
    """Unified payload accepting any/all confirmed AI Engine outputs in a single transaction."""
    camera_id: Optional[str] = Field(None, description="Optional camera ID if tracks are included")
    tracks: Optional[List[VehicleTrackInput]] = Field(None, description="Vehicle tracks observed at camera")
    matches: Optional[List[CrossCameraMatchInput]] = Field(None, description="Cross-camera pairwise matches")
    global_vehicles: Optional[List[GlobalVehicleInput]] = Field(None, description="Canonical global vehicles")
    trajectories: Optional[List[TrajectoryInput]] = Field(None, description="Trajectories with segments")
    predictions: Optional[List[RoutePredictionInput]] = Field(None, description="Route predictions")

    model_config = ConfigDict(extra="forbid")


class IngestResponse(BaseModel):
    """Standard response for ingestion endpoints."""
    success: bool
    message: str
    counts: dict
